/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Aline' at '05/12/16 19:43' with Gradle 3.2.1
 *
 * @author Aline, @date 05/12/16 19:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
